---
- name: Wait for system ready
  hosts: collator
  gather_facts: no
  tasks:
  - name: Wait for nodes to become reachable
    wait_for_connection:

- name: configure boot node
  hosts: collator
  become: yes
  roles:
  - polkadot-binary-installation
  - polkadot-collator-conf