---
- name: Wait for system ready
  hosts: rpc
  gather_facts: no
  tasks:
  - name: Wait for nodes to become reachable
    wait_for_connection:

- name: configure rpc node
  hosts: rpc
  become: yes
  roles:
  - polkadot-binary-installation
  - polkadot-rpc-installation