---
- name: Wait for system ready
  hosts: all
  gather_facts: no
  tasks:
  - name: Wait for nodes to become reachable
    wait_for_connection:

- name: install binary
  hosts: all
  become: yes
  roles:
  - polkadot-binary-installation